"""Generate the three inscription scripts via the REAL llm-rosetta converter.

Two canonical requests (the IR sources) are each converted to all three
provider dialects with the actual `convert()` tool — so the stone's three
script bands are genuine llm-rosetta output, not hand-written. Literal Rosetta
Stone: one decree, three scripts, produced by the translation engine itself.

Each band = its dialect's output for request 1 + request 2, hard-wrapped to a
fixed width so every line is full and the inscription packs edge-to-edge.

Writes scripts_data.py consumed by build_logo.py.
"""
from __future__ import annotations
import json
from pathlib import Path
from llm_rosetta import convert

HERE = Path(__file__).parent

# Two canonical requests — self-referential: the inscription is *about*
# llm-rosetta and the Rosetta Stone itself. The carved text is the project
# explaining what it is. Doubled content for density.
REQ1 = {
    "model": "gpt-5",
    "messages": [
        {"role": "system",
         "content": "You are llm-rosetta, a universal LLM API translator."},
        {"role": "user",
         "content": "Convert one request across OpenAI, Anthropic, and "
                    "Google formats, like the Rosetta Stone's three scripts."},
    ],
    "tools": [{"type": "function", "function": {
        "name": "convert_request",
        "description": "translate an LLM API payload between providers",
        "parameters": {"type": "object",
                       "properties": {"source": {"type": "string"},
                                      "target": {"type": "string"}},
                       "required": ["source", "target"]}}}],
    "tool_choice": "auto",
    "temperature": 0.2, "top_p": 0.9, "max_tokens": 256, "stream": True,
}
REQ2 = {
    "model": "gpt-5",
    "messages": [
        {"role": "system",
         "content": "You decode ancient and modern scripts alike."},
        {"role": "user",
         "content": "The Rosetta Stone bore one decree in three scripts; "
                    "llm-rosetta bears one request in many API dialects."},
    ],
    "tools": [
        {"type": "function", "function": {
            "name": "transliterate", "description": "render glyphs as text",
            "parameters": {"type": "object",
                           "properties": {"script": {"type": "string"},
                                          "lang": {"type": "string"}},
                           "required": ["script"]}}},
        {"type": "function", "function": {
            "name": "web_search",
            "description": "search the web for context on a query",
            "parameters": {"type": "object",
                           "properties": {"query": {"type": "string"},
                                          "max_results": {"type": "integer"}},
                           "required": ["query"]}}},
    ],
    "tool_choice": "auto",
    "temperature": 0.7, "max_tokens": 512, "stream": True,
}

WRAP = 92  # overrun right edge at all heights, clipped to full rows


def hard_wrap(s: str, width: int) -> list[str]:
    return [s[i:i + width] for i in range(0, len(s), width)]


def to_lines(*objs: dict) -> list[str]:
    out = []
    for o in objs:
        s = json.dumps(o, ensure_ascii=False, separators=(",", ":"))
        out += hard_wrap(s, WRAP)
    return out


def main() -> None:
    blocks = []
    for tgt in ("openai_chat", "anthropic", "google"):
        o1 = convert(REQ1, tgt, "openai_chat")
        o2 = convert(REQ2, tgt, "openai_chat")
        blocks.append((tgt, to_lines(o1, o2)))

    py = ['"""AUTO-GENERATED by gen_scripts.py — real convert() output. Do not edit."""',
          "", "SCRIPTS = ["]
    for name, lines in blocks:
        py.append(f"    ({name!r}, [")
        for ln in lines:
            py.append(f"        {ln!r},")
        py.append("    ]),")
    py.append("]")
    (HERE / "scripts_data.py").write_text("\n".join(py) + "\n")
    print("generated:", {n: len(l) for n, l in blocks},
          "total", sum(len(l) for _, l in blocks))


if __name__ == "__main__":
    main()
